### ISSUE TITLE
Can't print to stderr

### ISSUE THREAD

**Issue by henridwyer** [LightTable/Python#23]
When printing to stderr, nothing shows up in the console.
```python
    import sys
    print >> sys.stderr, "test"
```
```python
    import sys
    sys.stderr.write("test2")
```
Both of these ways work if you replace stderr with stdout.

This raises an error for both stderr and stdout:
```python
    from __future__ import print_function
    print('spam', file=sys.stderr)
```

```
Traceback (most recent call last):
  File "~/Library/Application Support/LightTable/plugins/Python/py-src/ltmain.py", line 267, in ipyEval
    compile(ensureUtf(code), ensureUtf(data[2]["name"]), 'exec')
  File "test.py", line 9
    print("test", file=sys.stdout)
                      ^
SyntaxError: invalid syntax
```

**Comment by hayd** [comment]
It's unclear if the stderr part is https://github.com/LightTable/Python/blob/134751c32a86699c06ccafe46ae73a17a0e2d012/py-src/ltipy.py#L222 or https://github.com/LightTable/Python/blob/134751c32a86699c06ccafe46ae73a17a0e2d012/py-src/ltipy.py#L199 (those are my guesses).

The print_function bug is different... scoping of exec?

**Comment by dosmoc** [comment]
Had a look at the print_function bug. It appears to be related to the fact LightTable compiles each form in the file in sequence in `py-src/ltmain.py`:

```python
  for form in toExec:
      code = form[1]
      loc = form[0]
      #conditional stuff for eval vs. exec
          code= compile(code, data[2]["name"], 'exec')
```

and the fact that the print_function is a monkey patch to syntax that exists only at runtime. 

Attaching the `from __future__ import print_function` line to the code in `py-src/ltmain.py` allows something like `print('spam', file=sys.stderr)` to be evaluated successfully:
```python
if "print" in code:
  code = "from __future__ import print_function\n" + code
 
code= compile(code, data[2]["name"], 'exec')
```

I'm not familiar with Python/LightTable internals, so can't propose an actual solution.
